spring:
    datasource: 
            c3p0: 
                driverClass: com.mysql.jdbc.Driver
                jdbcUrl: jdbc:mysql://localhost:3306/springboot
                user: root
                password: root
                maxPoolSize: 30
                minPoolSize: 10
                initialPoolSize: 10
  
    jpa: 
        showSql: true
        properties: 
            hibernate: 
              format_sql: true